### ISSUE TITLE
bug: order quantity not available in CoA rendered in PDF

### ISSUE THREAD

**Issue by stiebitzhofer** [s1seven/schema-tools#111]
# Description

**What keywords did you search in schema-tools issues before filing this one ?**
`PDF`

**Is this a BUG REPORT or FEATURE REQUEST ?**
`BUG`

**What you expected to happen :**
If `Order/Quantity` is not available it and `Order/QuantityUnit` should not be rendered on PDF is it results in `NaN undefined`. This will match the results of the HTML rendering.

<img width="990" alt="Problem if OrderQuantity is unknown" src="https://user-images.githubusercontent.com/581724/154806140-fc305240-1735-4513-9a96-4e0003d4c6fa.png">

**Comment by getlarge** [comment]
I guess the schema should be fixed first, currently `Order.Quantity` and `Order.QuantityUnit` are required properties.
Also i don't see any conditional rendering in the HBS template, so you mean to implement it too ?

**Comment by stiebitzhofer** [comment]
> I guess the schema should be fixed first, currently `Order.Quantity` and `Order.QuantityUnit` are required properties.
> Also i don't see any conditional rendering in the HBS template, so you mean to implement it too ?

You are right, it is required. As many example certificates do not include them we have to make it optional. You are also right on the HBS template. But let's address after the first round of review with user. In this I just add it to the list of known issues.
