### ISSUE TITLE
feat: use dynamic fonts based on languages

### ISSUE THREAD

**Issue by getlarge** [s1seven/schema-tools#117]
# Description

**Is this a BUG REPORT or FEATURE REQUEST ?** FEATURE

**What you expected to happen :**  

see : https://github.com/thematerials-network/CoA-schemas/issues/38

**How to reproduce it :** 

Use a certificate with `CN` CertificateLanguages.

- [ ] allow fonts to be dynamically loaded based on certificate languages

**Comment by christophbuehler** [comment]
The simple solution is to switch to NotoSansSC as a default font. Waiting for https://github.com/s1seven/schema-tools/issues/150.
