### ISSUE TITLE
bug: typo in PDF rendering of ChemicalElement/Minimum

### ISSUE THREAD

**Issue by stiebitzhofer** [s1seven/schema-tools#180]
# Description

**What keywords did you search in schema-tools issues before filing this one?**
-

**Is this a BUG REPORT or FEATURE REQUEST ?**
BUG

**Environment:**

**What you expected to happen:**
The header of the row should be `Maximum` not `Maximun`.

**How to reproduce it:**
Create a PDF
<img width="471" alt="Maximun" src="https://user-images.githubusercontent.com/581724/202865278-59fc6909-bc62-4424-84ec-af9b34a8f8ae.png">

**Comment by getlarge** [comment]
Fixed in #182.
