### ISSUE TITLE
bug: unit not render in PDF for `OtherMechanicalTests`

### ISSUE THREAD

**Issue by stiebitzhofer** [s1seven/schema-tools#198]
# Description

**What keywords did you search in schema-tools issues before filing this one ?**

**Is this a BUG REPORT or FEATURE REQUEST ?**
`BUG`

**Environment:**
`EN 10168 Schema version 0.4.1` on https://app.s1seven.com

**What you expected to happen:**
The unit given for key-value objects in the object `OtherMechanicalTests` is not rendered in PDFs. It is rendered correctly in HTML.

```JSON
"OtherMechanicalTests": {
  "C50": {
    "Key": "Verfestigungsversuch",
    "Value": "0.223",
    "Unit": "n-Wert",
    "Type": "number"
  }
}
```

**Rendering HTML:**
<img width="1190" alt="Bildschirm­foto 2023-02-23 um 14 57 02" src="https://user-images.githubusercontent.com/581724/220928648-f74fe10a-1f58-4627-bdf3-cf20880b3f58.png">

**Rendering PDF:**
<img width="627" alt="Bildschirm­foto 2023-02-23 um 14 56 15" src="https://user-images.githubusercontent.com/581724/220928601-c9ca5850-6f11-4606-abca-d7fe6eab1557.png">

**How to reproduce it:**
The used JSON can be shared private on request.

**Comment by getlarge** [comment]
The `OtherMechanicalTests` properties are rendered in [`renderOtherMechanicalTests`](https://github.com/s1seven/schema-tools/blob/main/packages/generate-en10168-pdf-template/src/lib/createInspection.ts#L258) and obviously the units are missing.

We could refactor the [`renderKVObjectTests`](https://github.com/s1seven/schema-tools/blob/main/packages/generate-en10168-pdf-template/src/lib/createOtherTests.ts#L67) function to make it usable in `renderOtherMechanicalTests` as well.
