### ISSUE TITLE
Ci: danger step should NOT run on main (push or merge)

### ISSUE THREAD

**Issue by getlarge** [s1seven/schema-tools#213]
# Description

The latest workflow just failed during merge because `danger` is now run during merge as well.
See : https://github.com/s1seven/schema-tools/actions/runs/4879728469/jobs/8706599658

@eamon0989 can you please add the condition that was probably already here before merging #208 ?

**Comment by eamon0989** [comment]
I found the problem, the `Extract branch name` step was accidentally removed from the ci which caused Danger to run even when merging to main. I've restored it in https://github.com/s1seven/schema-tools/pull/212
