### ISSUE TITLE
bug:  logo in EN 10168 rendering not responsive

### ISSUE THREAD

**Issue by stiebitzhofer** [s1seven/schema-tools#215]
# Description

**What keywords did you search in schema-tools issues before filing this one ?**
`HTML`

**Is this a BUG REPORT or FEATURE REQUEST ?**
`Bug`

**Environment:**
app.s1seven.dev

See https://github.com/material-identity/schema-definitions/issues/18

**Comment by stiebitzhofer** [comment]
@eamon0989 @getlarge @christophbuehler Just testing: can we take care of that issue soon?

**Comment by getlarge** [comment]
We can try to do it during this iteration, but i’m closing the issue here as this can only be done through the [schema-definition](https://github.com/material-identity/schema-definitions/blob/main/commercial-transaction/commercial-transaction.json ) repository.
