### ISSUE TITLE
feat: embed JSON into PDF rendering

### ISSUE THREAD

**Issue by christophbuehler** [s1seven/schema-tools#240]
# Description

Embed the certificate JSON into the PDF ~using the [PDF/A-3 standard](https://www.iso.org/standard/57229.html), which is intended for document archiving~.

**Comment by christophbuehler** [comment]
The current format of our PDFs is `PDF1.3`. `pdfmake` [does not support PDF/A](https://github.com/bpampuch/pdfmake/issues/950), so we have to convert the output file to `PDF/A` using another tool.

**Comment by christophbuehler** [comment]
PDF viewers capable of viewing attachments:
| Tool               | Can display attachments |
|--------------------|-------------------------|
| Acrobat Reader     | yes                     |
| Firefox            | yes                     |
| Chromium           | no                      |

Acrobat Reader:
<img width="810" alt="image" src="https://github.com/s1seven/schema-tools/assets/4547315/dab73fe5-8d57-4de6-a784-86c88772caf3">

**Comment by christophbuehler** [comment]
@stiebitzhofer [would this be according to your needs](https://github.com/s1seven/schema-tools/files/14300825/coa-test.pdf)?
<img width="703" alt="image" src="https://github.com/s1seven/schema-tools/assets/4547315/b9e64436-aa38-4420-9dfa-2db3497c785a">

**Comment by stiebitzhofer** [comment]
Looks great, I could extract the JSON (after finding a viewer capable). Now this is not a PDF/A-3 yet. Would you continue in a new issue?

One detail I see: in the latest version we moved to Noto, still Lato is embedded?

**Comment by christophbuehler** [comment]
> Looks great, I could extract the JSON (after finding a viewer capable). Now this is not a PDF/A-3 yet. Would you continue in a new issue?
> 
> 
> 
> One detail I see: in the latest version we moved to Noto, still Lato is embedded?

Which viewer did you end up using?I will update the table of supported viewers.

Yes, it is not a PDF/A. Is that a requirement by our customers? It is difficult to get that working without a cloud service, but I am happy to look into the options.

I believe the demo just needs to be updated to use different font files, this should not be a problem.

**Comment by stiebitzhofer** [comment]
I used https://foxit.com, which also displays the information on whether this is PDF/A or not. For fonts, you can see them in document properties:
<img width="608" alt="Bildschirmfoto 2024-02-16 um 09 21 01" src="https://github.com/s1seven/schema-tools/assets/581724/04117b88-e527-4fd5-bda6-da2d78f9b1de">

**Comment by christophbuehler** [comment]
> I used https://foxit.com, which also displays the information on whether this is PDF/A or not. For fonts, you can see them in document properties:
> 
> <img width="608" alt="Bildschirmfoto 2024-02-16 um 09 21 01" src="https://github.com/s1seven/schema-tools/assets/581724/04117b88-e527-4fd5-bda6-da2d78f9b1de">
> 
> 
> 
> 

Is it a requirement that we have a PDF/A?

**Comment by getlarge** [comment]
@christophbuehler I was digging into the pdfmake repository and landed on this [PR](https://github.com/bpampuch/pdfmake/pull/2227/) that enables attachment. Did you give it a try already?

**Comment by stiebitzhofer** [comment]
@getlarge Christoph got it already working, JSON attachment plus all the little additions to make it PDF/A-3 compliant. So, I assume he is using that.
