### ISSUE TITLE
feat: make the PDF read only

### ISSUE THREAD

**Issue by stiebitzhofer** [s1seven/schema-tools#251]
# Description

**What keywords did you search in schema-tools issues before filing this one ?**
-

**Is this a BUG REPORT or FEATURE REQUEST ?**
FEATURE

**What you expected to happen:**
The attribute `permissions.modifying` shall be set to `false`. The reasoning is that PDF Readers warn the user that the document will lose PDF/A compliance in case of modifications. 

<img width="1116" alt="Bildschirmfoto 2024-03-02 um 12 43 10" src="https://github.com/s1seven/schema-tools/assets/581724/f2549702-8643-455f-a265-59c17e9ad706">

Outline:

```JS
const docDefinition = {
  permissions: {
    modifying: false
  }
}
```

**Comment by christophbuehler** [comment]
[The feature to add permissions in pdf-lib](https://github.com/Hopding/pdf-lib/issues/472) is on the [roadmap](https://github.com/Hopding/pdf-lib/discussions/998). It may be possible to already achieve this using low-level apis, but I suggest postponing this until it is officially supported.

**Comment by stiebitzhofer** [comment]
Ok
